version: "3"
services:
  seqcli:
    image: datalust/seqcli:latest
    command: apikey create -t Undercover --token sLUq1trorcQ0tbaiKCUD -s http://seq
    depends_on:
      - seq
    restart: on-failure
    networks:
      - seqnetwork
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8003:80"
      - "5341:5341"
    networks:
      - seqnetwork
networks:
  seqnetwork: