# Server configurations
server:
  host: "localhost"
  port: 8080
  endpoint: "ws"

# Seq credentials
seq:
  url: "http://localhost:5341"
  apikey: "sLUq1trorcQ0tbaiKCUD"

game:
  nbUndercover: 1
  nbWhite: 1
  nbTurn: 1
